(function(){var m=this;var H="1.1.40";var A={};var w=["cuid","type","itemId","itemName","itemImage","itemUrl","originalPrice","salePrice","category1","category2","category3","category4","category5","regDate","updateDate","expireDate","stock","state","description","extraImage","locale"];
m.callback=null;var z=function(Q,M){var O;var f=location.href;var P=(f.slice(f.indexOf("?")+1,f.length)).split("&");if(!!M&&M==true){O={};for(var N=0;N<P.length;
N++){var R=P[N].split("=")[0];if(R.indexOf(Q)>=0){O[R]=P[N].split("=")[1];}}return O;}else{for(var N=0;N<P.length;N++){var R=P[N].split("=")[0];if(R.toUpperCase()==Q.toUpperCase()){O=P[N].split("=")[1];
return decodeURIComponent(O);}}}};function l(f){var M=document.getElementsByTagName("meta");for(i=0;i<M.length;i++){if(M[i].getAttribute("property")==f){return M[i].getAttribute("content");
}}return"";}function a(){var O={};for(var f in w){var N="ca:"+w[f];var M=l(N);if(!!M){O[w[f]]=M;}}return O;}function u(){var f={};for(var M in w){var O="rb:"+w[M];
var N=l(O);if(!!N){f[w[M]]=N;}}return f;}function r(){var M=document.createElement("a");M.href=document.referrer;if(!!M.hostname&&M.hostname!==location.hostname){B("cauly_ref",M.hostname);
}var f=z("cauly_",true);var P=z("cauly_egmt_sec",false);var O=z("cauly_rt_code",false);if(!!f&&!!O){var N=Date.now()+"";B("cauly_ltime",N);var Q=JSON.stringify(f);
if(!!P){B("CAULY_PARAM",Q,P);}else{B("CAULY_PARAM",Q,600000);}}}function K(){var P={};try{var Q=k("CAULY_PARAM");if(!!Q){var S=JSON.parse(Q);var N=1;var O=0;
for(param in S){if("cauly_rt_code"==param){O=N;}P["param_"+N]=S[param];N++;}if(1<O){var f=P["param_"+O];P["param_"+O]=P.param_1;P.param_1=f;}}if(window.caulyJSInterface){var M=window.caulyJSInterface.getParam("cauly_rt_code");
if(!!M&&M.length>0){P.param_1=M;}}}catch(R){}return P;}function F(){var f={};try{var M=k("CAULY_PARAM");if(!!M){var O=JSON.parse(M);for(param in O){f[param]=O[param];
}}else{return null;}}catch(N){}return f;}function k(M){var N=c(M);var f=q(M);if(N){return N;}else{if(f){return f;}}return"";}function B(f,N,M){n(f,N,M);
C(f,N);}function C(f,M){try{if(!!window.localStorage){localStorage.removeItem(f);localStorage.setItem(f,M);}else{if(navigator.cookieEnabled){return n(f,M);
}}}catch(N){try{n(f,M);}catch(N){}return true;}return false;}function q(f){try{if(!!window.localStorage){return localStorage.getItem(f);}else{if(navigator.cookieEnabled){return c(f);
}}}catch(M){try{return c(f);}catch(M){return"";}}return"";}function c(O){var M=O+"=";var f=document.cookie.split(";");for(var N=0;N<f.length;N++){var P=f[N].replace(/(^\s*)|(\s*$)/gi,"");
if(P.indexOf(M)==0){return P.substring(M.length,P.length);}}return"";}function n(N,P,O){if(navigator.cookieEnabled){try{if(!!O){var M=new Date();M.setTime(M.getTime()+(O*1000));
var f="; expires="+M.toGMTString();document.cookie=N+"="+P+f+";path=/;";}else{var R=new Date();R.setTime(R.getTime()+(1000*24*60*60*1000));var f="expires="+R.toUTCString()+";";
document.cookie=N+"="+P+";path=/;"+f;}return true;}catch(Q){return false;}}return false;}function J(){if("Android"==E().platform){return true;}return false;
}function y(){if("iPhone"==E().platform||"iPad"==E().platform){return true;}return false;}function g(M,f){if(M){return D(f);}else{return b(f);}}function b(M){var f=M.match(/OS\s([0-9\_]*)/);
if(f){return f[1].replace(/_/gi,".");}return"1.1.0";}function D(M){var M=M||navigator.userAgent;var f=M.match(/Android\s([0-9\.]*)/);return f?f[1]:"1.1.0";
}function L(M){var f=M.match(/\s([A-Za-z0-9\-_]*) Build/);return f?f[1]:"";}function E(){var N={};var M=navigator.userAgent;var f=M.toLowerCase();if(f.indexOf("iphone")>=0||M.indexOf("ipod")>=0){N.platform="iPhone";
N.version=g(false,M);N.model="";}else{if(f.indexOf("ipad")>=0){N.platform="iPad";N.version=g(false,M);N.model="";}else{if(f.indexOf("firefox")>=0||f.indexOf("opera")>=0){N.platform="Android";
N.version="4.0.0";N.model="";}else{if(f.indexOf("android")>=0){N.platform="Android";N.version=g(true,M);N.model=L(M);}else{N.platform="unknown";N.version="";
N.model="";}}}}return N;}var v=function(){var O=/(\W|^)(fban|fbios|fbav|fbid|fb_iad)/g.test(navigator.userAgent.toLowerCase());var N=navigator.userAgent;
var f=N.toLowerCase();var M="";if(f.indexOf("daum")>=0){M="daum";}else{if(f.indexOf("naver")>=0){M="naver";}else{if(f.indexOf("kakao")>=0){M="kakao";}else{if(f.indexOf("samsung")>=0){M="samsung";
}else{if(f.indexOf("instagram")>=0){M="instagram";}else{if(f.indexOf("nate")>=0){M="nate";}else{if(O){M="facebook";}else{if(f.indexOf("wv")>=0||f.indexOf("inapp")>=0){M="webview";
}else{if(f.indexOf("chrome")>=0){M=f.substr(f.indexOf("chrome")).split(" ")[0];}else{if(f.indexOf("safari")>=0){M=f.substr(f.indexOf("safari")).split(" ")[0];
}else{if(f.indexOf("msie")>=0){M=f.substr(f.indexOf("msie")).split(";")[0];}else{if(f.indexOf("firefox")>=0){M=f.substr(f.indexOf("firefox")).split(" ")[0];
}else{M="";}}}}}}}}}}}}return M;};var d=function(N){var M=N.data;if(N.origin.indexOf("image.cauly.co.kr")>=0){if(M.cauly_code=="send_cauly_scode"){B(N.data.type,N.data.scode);
}else{if(M.indexOf("caulytracker_cid:")>=0){try{var f=M.replace("caulytracker_cid:","");B("CT_CID",f);if(m.callback){m.callback(f);m.callback=null;}}catch(N){}}}}};
m.InfoBuilder={trackcode:"",gender:"",userid:"",age:"",devmode:false,setTrackCode:function(f){m.InfoBuilder.sitecode=f;return m.InfoBuilder;},setGender:function(f){m.InfoBuilder.gender=f;
return m.InfoBuilder;},setAge:function(f){m.InfoBuilder.age=f;return m.InfoBuilder;},setUserId:function(f){m.InfoBuilder.userid=f;return m.InfoBuilder;
},setDevMode:function(f){m.InfoBuilder.devmode=f;return m.InfoBuilder;},build:function(){return{track_code:m.InfoBuilder.sitecode,gender:m.InfoBuilder.gender,user_id:m.InfoBuilder.userid,age:m.InfoBuilder.age};
}};var p={target:"https://image.cauly.co.kr/script",id:"c_i"+(new Date().getTime()),iframe:null};var I={msgQueue:new Array(),isIfreameLoaded:false,make_iframe:function(){if(p.iframe!=null){return;
}if(typeof window.addEventListener!="undefined"){window.addEventListener("message",d,false);}else{if(typeof window.attachEvent!="undefined"){window.attachEvent("onmessage",d);
}}var f=z("caulytracker_file",false);if(!f){f="caulytracker4.html";}p.iframe=document.createElement("iframe");p.iframe.src=p.target+"/"+f;p.iframe.scrolling="no";
p.iframe.border="0";p.iframe.setAttribute("width","1");p.iframe.setAttribute("height","1");p.iframe.setAttribute("frameBorder","0");p.iframe.style.display="none";
p.iframe.onload=function(){if(m.InfoBuilder.devmode==true){p.iframe.contentWindow.postMessage("cauly_dev_mode",p.target);}I.isIfreameLoaded=true;for(var M=0;
M<I.msgQueue.length;M++){var N=I.msgQueue[M];N=G(N);p.iframe.contentWindow.postMessage([N],p.target);}I.msgQueue=[];};if(!!document.body){document.body.appendChild(p.iframe);
}else{document.getElementsByTagName("head")[0].appendChild(p.iframe);}},send_message:function(f){f=G(f);if(I.isIfreameLoaded==true){p.iframe.contentWindow.postMessage([f],p.target);
}else{I.msgQueue.push(f);}}};function o(M){var N="&";for(var f in M){N=N+f+"="+encodeURIComponent(M[f])+"&";}return N;}function s(P){var S=o(P);S=S+"unique_app_id="+encodeURIComponent(document.location);
var M="/event";M=x(S);var O=location.protocol+"//tracker.cauly.co.kr";var R=E();var Q=[O,M,"?sdk_type=web&lang=ko","&version=",R.version,"&platform=",R.platform,"&browser=",v(),"&egid=",k("cauly_egid")||"","&eaid=",k("cauly_eaid")||"","&model=",R.model,"&scode=",m.getStoredCID(),S].join("");
var N=document.getElementsByTagName("script")[0];var f=document.createElement("script");f.type="text/javascript";f.src=Q;N.appendChild(f);N.parentNode.insertBefore(f,N);
}function x(f){if(f.indexOf("&order_id=")>=0&&f.indexOf("&order_price=")>=0&&f.indexOf("&pruduct_infos=")>=0){return"/purchase";}return"/event";}function G(M){if(window.caulyJSInterface){var f=window.caulyJSInterface.getAdId();
if(y()){M.idfa=f;}else{if(J()){M.gid=f;}}}if(window.LOOKETAPPS){var f=window.LOOKETAPPS.rbGetAdId();if(J()){M.gid=f;}else{if(y()){M.idfa=f;}}}else{var f=k("looketappsadid");
if(!!f){if(J()){M.gid=f;}else{if(y()){M.idfa=f;}}}}return M;}function t(M,Q,f){var R={};for(var O in M){if("site_code"==O){R.track_code=M[O];}else{R[O]=M[O];
}}for(var N in Q){R[N]=Q[N];}if(typeof f!="undefined"&&f!=null){R.param_etc=JSON.stringify(f);}R.cauly_meta=JSON.stringify(a());R.rb_meta=JSON.stringify(u());
R.sdk_version=H;R.browser=v();R.egid=k("cauly_egid")||"";R.eaid=k("cauly_eaid")||"";R.page=location.href;var P=k("RB_GCID");if(P&&typeof P=="string"&&P.length>0){R.partner_id=P;
}R.t=new Date().getTime()/1000;return R;}function h(O){var Q=K();var P=k("cauly_ref");if(!!P){Q.param_4=P;}if(!!Q){var R=k("cauly_ltime");if(typeof R!="undefined"&&!isNaN(R)){var f=Number(R);
if(f>0){var N=Date.now();Q.param_2="conv_sec:"+parseInt((N-f)/1000);}}for(var M in Q){O[M]=Q[M];}}return O;}function j(){var M="";if(window.caulyJSInterface){var f=window.caulyJSInterface.getAdId();
if(y()){M=f;}else{if(J()){M=f;}}}if(M.length>0){if(J()){return"MA";}else{return"MI";}}if(J()||y()){return"MW";}return"PW";}function e(){var M=document.createElement("iframe");
M.src="//image.cauly.co.kr/websdk/common/lasted/template/get_scode.html";M.setAttribute("scrolling","no");M.setAttribute("marginheight","0");M.setAttribute("marginwidth","0");
M.setAttribute("frameborder","0");M.setAttribute("height","0px");M.style.display="none";M.style.width="0px";var f=(location.origin)?location.origin:location.protocol+"//image.cauly.co.kr";
M.onload=function(){M.contentWindow.postMessage({cauly_code:"script_param_url",script_param_url:f},location.protocol+"//image.cauly.co.kr");};document.body.appendChild(M);
}m.trackEvent=function(N,O,f){if(typeof N=="object"){var M=t(A,N);M=h(M);I.send_message(M);}else{if(typeof O=="undefined"||O==null){O={};}if(typeof O=="string"){O={event_param:O};
}O.event_name=N;var M=t(A,O,f);M=h(M);I.send_message(M);}};m.startSession=function(){var f=t(A,{event_name:"session",event_param:"start"});I.send_message(f);
};m.closeSession=function(){var f=t(A,{event_name:"session",event_param:"close"});I.send_message(f);};m.init=function(){A={};var R={};var f={};var N={};
var M=false;setTimeout(function(){e();},10);I.make_iframe();for(var O=0;O<window._paq.length;O++){var Q=_paq[O];if(Q&&Q.length>0){var P=Q[0];if("age"==P){A.age=Q[1];
}else{if("gender"==P){A.gender=Q[1];}else{if("track_code"==P){A.track_code=Q[1];}else{if("user_id"==P){A.user_id=Q[1];}else{if("event_name"==P){R.event_name=Q[1];
}else{if("event_param"==P){R.event_param=Q[1];}else{if("event_param"==P){R.event_param=Q[1];}else{if("order_id"==P){N.order_id=Q[1];}else{if("order_price"==P){N.order_price=Q[1];
}else{if("purchase_type"==P){N.purchase_type=Q[1];}else{if("product_infos"==P){N.pruduct_infos=JSON.stringify(Q[1]);}else{if("etc_param"==P){f.etc_param=Q[1];
}else{if("exclude_rb"==P){M=true;}else{if("send_event"==P){if(N.order_id!=null&&N.order_id.length>0){m.trackEvent(N,R.event_param,f.etc_param);}else{m.trackEvent(R.event_name,R.event_param,f.etc_param);
}R={};f={};N={};}}}}}}}}}}}}}}}}window._paq=[];};m.getStoredCID=function(){var f=k("CT_CID");if(f&&f.indexOf("CID")==0){return f;}return"";};m.getCID=function(N,f){if(f==null||typeof f=="undefined"){f=5000;
}var M=k("CT_CID");if(M&&M.indexOf("CID")==0){N(M);}else{m.callback=N;setTimeout(function(){if(m.callback){m.callback("");}},f);}};m.getCID2=function(O,N,f){if(f==null||typeof f=="undefined"){f=5000;
}var M=k("CT_CID");if(M&&M.indexOf("CID")==0){O(M);}else{m.callback=O;setTimeout(function(){var P=m.getStoredCID();if(!!P&&P.indexOf("CID")==0){if(!!m.callback){m.callback(P);
}}else{if(!!N){if("unknown"==E().platform){N("support in mobile");}else{N("cannot create CID");}}}},f);}};setTimeout(function(){r();m.init();},0);})();
